### ISSUE TITLE
What to do with js files?

### ISSUE THREAD

**Issue by roopesh** [carlos-sarmiento/ha-iconset-generator#1]
I finally got back around to this.  I ran everything, generated the js files, and put them in `config/custom_components/fontawesome/data`.  But icons e.g. `fal:` still don't load.  Do I need to make other modifications?

**Comment by carlos-sarmiento** [comment]
You can either:

1. Install the hass-fontawesome component and then replace the JS files
2. Add the files to the `config/www` folder and then reference them as Lovelace resources (instructions on how to get to the lovelace resources page are here: https://community.home-assistant.io/t/adding-resources-to-lovelace/180729)

**Comment by Jens-Wymeersch** [comment]
@carlos-sarmiento I've followed your guide and created the js files and replaced the JS files but still can't get them loaded. Any ideas ?

**Comment by carlos-sarmiento** [comment]
Updated the Readme files with these instructions
