### ISSUE TITLE
JS Syntaxe

### ISSUE THREAD

**Issue by Robvred** [carlos-sarmiento/ha-iconset-generator#2]
Hello,

A small syntax error in the custom configuration code:

{
    "outputPath": "js/v5-pro", // Where should the generated JS files be written.
    "iconsets": [ // An Array of iconsets to generate.
        {
            "directory": "icons/v5-pro/brands", // The path in which the .svg files can be found
            "name": "fab" // The name of the generated iconset. Used both for the js file and the ha prefix
        },
    ]
}

Instead of :
{
    "outputPath": "js/v5-pro", // Where should the generated JS files be written.
    "iconsets": [ // An Array of iconsets to generate.
        {
            "directory": "icons/v5-pro/brands", // The path in which the .svg files can be found
            "name": "fab" // The name of the generated iconset. Used both for the js file and the ha prefix
        }
    ]
}

Unexpected comma at ' },'

Thanks for this perfect solution ! 👍

**Comment by carlos-sarmiento** [comment]
Thanks for reporting, but I don't see that comma on the full conf file. It looks like it was modified locally and the comma was not removed there.

**Comment by Robvred** [comment]
Hello @carlos-sarmiento,

I was not really precise, the typo is in the Readme.md file

<img width="858" alt="Capture d’écran 2021-01-24 à 19 59 48" src="https://user-images.githubusercontent.com/12579254/105640549-ff79e180-5e7e-11eb-8fec-0cc13233510d.png">

**Comment by carlos-sarmiento** [comment]
Thanks for reporting. It is fixed.
